### ISSUE TITLE
Show previews for more file types like PDF etc.

### ISSUE THREAD

**Issue by Sanookmakmak** [keeporsweep/keeporsweep#13]
... of pregenerated images of the preview generator app https://apps.nextcloud.com/apps/previewgenerator

**Comment by MorrisJobke** [comment]
What does this ticket mean? We should not delete previews IMO. cc @rullzer

**Comment by rullzer** [comment]
Well you can. But it is kind of pointless as they will be regenerated if you for example open the sidebar on the original file.

**Comment by jancborchardt** [comment]
Yeah, this is a bit of a useless action too, as it's not deleting actual data.

Closing this issue as we're not likely to implement this. If you mean that we should also remove the preview images of files which are removed through Keep or Sweep – that should already happen and if not would be a bug in the preview generator I guess.

**Comment by Sanookmakmak** [comment]
> What does this ticket mean?

@MorrisJobke  For example, when a PDF file is opened by the app, it does not display the content of the PDF file, it displays the PDF icon and underneath is the filename which i don't remeber what was the content of the file. But if the app would display the preview of the file it would be easier to remember what's inside the file.

**Comment by MorrisJobke** [comment]
Ah – so it should just use previews. This makes sense

**Comment by jancborchardt** [comment]
Absolutely, good point @Sanookmakmak, sorry for the misunderstanding. :) Edited the title to clarify, and reopening.

**Comment by jancborchardt** [comment]
@Sanookmakmak so this should work as long as you have PDF previews enabled on your server. Same for the other file types. :)
