### ISSUE TITLE
Nextcloud 15 reupload

### ISSUE THREAD

**Issue by MorrisJobke** [keeporsweep/keeporsweep#20]
Hey,

as the info.xml already holds the Nextcloud 15 flag it should be enough to re-upload the existing release so it is properly parsed in the app store. We enabled 15 uploads last week.

**Comment by MorrisJobke** [comment]
@jancborchardt Ping ;)

**Comment by jancborchardt** [comment]
@MorrisJobke actually I’m having issues, the content is staying empty and there’s this console error on CSP:
```
[Vue warn]: It seems you are using the standalone build of Vue.js in an environment with Content Security Policy that prohibits unsafe-eval. The template compiler cannot work in this environment. Consider relaxing the policy to allow unsafe-eval or pre-compiling your templates into render functions.
```
How do I fix that?

**Comment by MorrisJobke** [comment]
> How do I fix that?

Compile the Vue templates. Our default CSP forbids `eval()` because it's the last biggest attack vector we had.

Or: you could overwrite this policy in your app if needed. Preferably not, but if compiling is not an option at all so be it.

**Comment by jancborchardt** [comment]
@MorrisJobke thanks! Any pointers on how I can do either (compiling Vue templates here or overwrite the CSP policy)?

**Comment by jancborchardt** [comment]
Cause I think compiling is not really an option at least not for the 15 release. There is a rewrite of the frontend underway so then I guess the templates will already be compiled.

**Comment by jancborchardt** [comment]
@MorrisJobke I mean, yes that’s  what the warning message says. ;) Now I found a docs page and did things it says (I think) but it doesn’t change anything.

To `lib/Controller/PageController.php` I added:
```
use OCP\AppFramework\Http\ContentSecurityPolicy;
```
And then in the index function:
```
$csp = new ContentSecurityPolicy();
$csp->allowEvalScript(true);
$response->setContentSecurityPolicy($csp);
```

**Comment by MorrisJobke** [comment]
Does your method ends in this?

```php
return $response;
```

**Comment by jancborchardt** [comment]
@MorrisJobke ah, no it didn’t. Now it does but still the same error. The full PageController.php looks like this:
```
<?php
namespace OCA\KeepOrSweep\Controller;

use OCP\IRequest;
use OCP\AppFramework\Http\TemplateResponse;
use OCP\AppFramework\Http\DataResponse;
use OCP\AppFramework\Controller;
use OCP\AppFramework\Http\ContentSecurityPolicy;

class PageController extends Controller {
	private $userId;

	public function __construct($AppName, IRequest $request, $UserId){
		parent::__construct($AppName, $request);
		$this->userId = $UserId;
	}

	/**
	 * CAUTION: the @Stuff turns off security checks; for this page no admin is
	 *          required and no CSRF check. If you don't know what CSRF is, read
	 *          it up in the docs or you might create a security hole. This is
	 *          basically the only required method to add this exemption, don't
	 *          add it to any other method if you don't exactly know what it does
	 *
	 * @NoAdminRequired
	 * @NoCSRFRequired
	 */
	public function index() {
		return new TemplateResponse('keeporsweep', 'index');  // templates/index.php
		$csp = new ContentSecurityPolicy();
        $csp->allowEvalScript(true);
        $response->setContentSecurityPolicy($csp);

		return $response;
	}

}

```



Modifying to this as per the docs page:
```
$csp->allowEvalScript(true);
    ->allowInlineScript(true);
    ->allowInlineStyle(true);
``
Shows a Nextcloud error page.

**Comment by jancborchardt** [comment]
Ah I think I got it …

**Comment by jancborchardt** [comment]
Of course, it was the return statement above … needed to edit to:
```
$response = new TemplateResponse('keeporsweep', 'index');
```
thanks a lot @MorrisJobke! :)

**Comment by jancborchardt** [comment]
I still get this warning in the console but I guess it can be ignored?
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```

I can’t see any issues it causes.

**Comment by jancborchardt** [comment]
Aaand released! :shipit:  Thanks a lot @MorrisJobke 

- App store: https://apps.nextcloud.com/apps/keeporsweep
- Release on Github: https://github.com/keeporsweep/keeporsweep/releases/tag/v0.2.1
