### ISSUE TITLE
KeepOrSweep only displayed in upper left corner

### ISSUE THREAD

**Issue by phischmi** [keeporsweep/keeporsweep#21]
I installed KeepOrSweep via Nextcloud and since then, it is only displayed in the upper left corner of the screen. I'm using Nextcloud 14.0.4.

![KeepOrSweep](https://up.picr.de/34430167bn.jpg)

**Comment by jancborchardt** [comment]
Yep, the issue was fixed with https://github.com/keeporsweep/keeporsweep/pull/19 → I need to do a new release. :)

**Comment by jancborchardt** [comment]
This is now released! https://apps.nextcloud.com/apps/keeporsweep :slightly_smiling_face: 

Sorry for the delay!
