### ISSUE TITLE
Alignment broken with Nextcloud 17

### ISSUE THREAD

**Issue by sephrat** [keeporsweep/keeporsweep#26]
Hi,

I'm using Nextcloud 17 and there seems to be a padding/margin issue in the top:
![image](https://user-images.githubusercontent.com/34862846/69051683-52e3da80-0a05-11ea-9567-23cb1a231123.png)
The header hides the beginning of the page.
It happens on desktop and mobile.

Changing padding of #app-content from 1em to 3em looks better, I'm not sure that's a proper fix though.

**Comment by nitink4472** [comment]
Would i make a PR to set the padding to 3em. Is that the issue?

**Comment by sephrat** [comment]
It would fix it for Nextcloud 17 but I'm not sure how it will behave with other versions of Nextcloud.

**Comment by nitink4472** [comment]
Have you used other versions of it? bcoz if it would be behaving the same with others, then it could be set to 3em?

**Comment by sephrat** [comment]
I can only speak for Nextcloud 17 since that's the only version I'm using, sorry.
However I suspect the display is fine with 1em in older versions since I'm the only one reporting this and v17 is quite new.

**Comment by jancborchardt** [comment]
I tested with Nextcloud 17 and 18 and I can’t reproduce the issue here. @nitink4472 can you reproduce it?

**Comment by nitink4472** [comment]
> I tested with Nextcloud 17 and 18 and I can’t reproduce the issue here. @nitink4472 can you reproduce it?
So, that means the problem exists in Nextcloud 18 too. Isn't it? Just to confirm @jancborchardt .

**Comment by sephrat** [comment]
I didn't mention I encountered the issue in Chrome (Windows + Android). 
I just tested it with Firefox and the display is OK, both on Windows and Android.
IE gives different yet broken result as well.
![image](https://user-images.githubusercontent.com/34862846/71617901-9bbeaf80-2bbd-11ea-84cd-5e649a3ec5af.png)

**Comment by nitink4472** [comment]
> I didn't mention I encountered the issue in Chrome (Windows + Android).
> I just tested it with Firefox and the display is OK, both on Windows and Android.
> IE gives different yet broken result as well.
> ![image](https://user-images.githubusercontent.com/34862846/71617901-9bbeaf80-2bbd-11ea-84cd-5e649a3ec5af.png)

@jancborchardt Is this the version issue?

**Comment by nitink4472** [comment]
May be?

**Comment by jancborchardt** [comment]
Keep or Sweep was finally updated to work with the latest Nextcloud release! :) I can not reproduce the issue anymore with Nextcloud 27 and 28.
- App store page: https://apps.nextcloud.com/apps/keeporsweep
- Release post on GitHub with more details: https://github.com/keeporsweep/keeporsweep/releases/tag/v0.3.0

Sorry for the long silence in development – if there are any issues, please open them here. :heart:
