### ISSUE TITLE
Add hotkeys for keep and sweep, like K and S or arrows keys

### ISSUE THREAD

**Issue by Blauschirm** [keeporsweep/keeporsweep#27]
Hey,
I love this extension and currently using it to sort through a lot of photos so I would love to be able to lay back and have my mousehand free by using hotkeys to interact with the plugin.
S and K would work perfectly, they are on the same row, and the directions are the same as the buttons. alternativly maybe the arrowkeys?

Thank you for your nextcloud support :)

**Comment by jancborchardt** [comment]
Heyhey @Blauschirm, thanks for your interest and sorry for the late reply! Actually shortcuts already exist:
- Keep: Space, →, Enter
- Sweep: Delete, ←

But they were only fixed again recently by https://github.com/keeporsweep/keeporsweep/pull/24 and need a release – I’ll get on that. :)

**Comment by jancborchardt** [comment]
Keep or Sweep including the mentioned shortcuts was finally updated to work with the latest Nextcloud release! :)
- App store page: https://apps.nextcloud.com/apps/keeporsweep
- Release post on GitHub with more details: https://github.com/keeporsweep/keeporsweep/releases/tag/v0.3.0

Sorry for the long silence in development – if there are any issues, please open them here. :heart:
