### ISSUE TITLE
Nextcloud 20 support

### ISSUE THREAD

**Issue by sunjam** [keeporsweep/keeporsweep#28]
Please update for Nextcloud 20 (and version 19 as well).  Thanks for considering!

**Comment by Kingofwizard** [comment]
There is really no need to! 
I've just tried for myself and the only "issue" that is present with nextcloud 19+ is that for some reasons it cannot unzip it.
but u can install it by yourself if you want to
Here are the steps needed to do so: 

sudo su
apt-get install git-core composer
cd /var/www/nextcloud/apps/   # or whatever your path to Nextcloud is, do "sudo find / | grep -i nextcloud/apps" to find out.
git clone https://github.com/keeporsweep/keeporsweep.git
cd keeporsweep
make
cd ..
sudo -u www-data php ./occ app:enable keeporsweep

and there you have it!
Later on if you want to update the app just do:

sudo su
cd /var/www/nextcloud/apps/   # or whatever your path to Nextcloud is, do "sudo find / | grep -i nextcloud/apps" to find out.
git pull
make

Hope this helps!

**Comment by junpet** [comment]
It would be better if we could install and update through the app store. Please make it compatible with Nextcloud 20+.

**Comment by quintz** [comment]
> 
> 
> There is really no need to!
> I've just tried for myself and the only "issue" that is present with nextcloud 19+ is that for some reasons it cannot unzip it.
> but u can install it by yourself if you want to
> Here are the steps needed to do so:
> 
> sudo su
> apt-get install git-core composer
> cd /var/www/nextcloud/apps/ # or whatever your path to Nextcloud is, do "sudo find / | grep -i nextcloud/apps" to find out.
> git clone https://github.com/keeporsweep/keeporsweep.git
> cd keeporsweep
> make
> cd ..
> sudo -u www-data php ./occ app:enable keeporsweep
> 
> and there you have it!
> Later on if you want to update the app just do:
> 
> sudo su
> cd /var/www/nextcloud/apps/ # or whatever your path to Nextcloud is, do "sudo find / | grep -i nextcloud/apps" to find out.
> git pull
> make
> 
> Hope this helps!

Unfortunately this didn't do the trick with me

**Comment by jancborchardt** [comment]
Keep or Sweep was finally updated to work with the latest Nextcloud release! :)
- App store page: https://apps.nextcloud.com/apps/keeporsweep
- Release post on GitHub with more details: https://github.com/keeporsweep/keeporsweep/releases/tag/v0.3.0

Sorry for the long silence in development – if there are any issues, please open them here.
