### ISSUE TITLE
remove this obsolete app from apps.nextcloud.com please

### ISSUE THREAD

**Issue by p-bo** [keeporsweep/keeporsweep#29]
Hello,
would it be possible to follow instructions on:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

and remove your past app:

https://apps.nextcloud.com/apps/keeporsweep

and help through this to tidy up the Nextcloud App store (most importantly it clutters apps catalogue in every Nextcloud instance) a bit please?

Thanks and have a nice day

**Comment by p-bo** [comment]
Or update it ;-)

Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by jancborchardt** [comment]
Keep or Sweep was finally updated to work with the latest Nextcloud release! :)
- App store page: https://apps.nextcloud.com/apps/keeporsweep
- Release post on GitHub with more details: https://github.com/keeporsweep/keeporsweep/releases/tag/v0.3.0

Sorry for the long silence in development – if there are any issues, please open them here.

**Comment by melroy89** [comment]
Great!
