### ISSUE TITLE
Previews not loaded on big instances

### ISSUE THREAD

**Issue by jancborchardt** [keeporsweep/keeporsweep#5]
I installed the app on my own instance, and no previews are shown:
![screenshot from 2018-03-29 20-32-44](https://user-images.githubusercontent.com/925062/38106841-8aa9e042-3390-11e8-9694-0c9c6579be50.png)

Any idea @camilasan @xMartin? @xMartin do I remember correctly that you also installed it on your own instance – do you see the same issue? Or is it maybe a missing package on my end?

**Comment by camilasan** [comment]
@jancborchardt do you see any error on the Console or in the Network (right click/Inspect)?

**Comment by jancborchardt** [comment]
@camilasan nothing in the console, but Network indeed. I’m seeing some "302 (Moved Temporarily)":

![screenshot from 2018-04-07 22-42-33](https://user-images.githubusercontent.com/925062/38460185-405a791c-3ab5-11e8-87af-60f40b15e5f9.png)

Headers:
![screenshot from 2018-04-07 22-44-09](https://user-images.githubusercontent.com/925062/38460184-402b65be-3ab5-11e8-881e-9e0b304c9655.png)

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Well that endpoint is only available on master.

If you want to use the old endpoint you need to construct the path for the requesting user.

**Comment by jancborchardt** [comment]
@rullzer ah ok, thanks! :)

Can you spill some more info for less apt programmers (like me ;) should I:
- Edit the preview URL here in the JS https://github.com/keeporsweep/keeporsweep/blob/master/js/script.js#L57 (and to what, and will that still work on master?
- Or already here in the PHP? https://github.com/keeporsweep/keeporsweep/blob/master/lib/Controller/ApiController.php#L28

**Comment by rullzer** [comment]
In the JS it seems.

Basically https://github.com/keeporsweep/keeporsweep/blob/master/js/script.js#L39 need to be `file: /path/to/the/file.jpg` or whatever.

**Comment by jancborchardt** [comment]
Fixed by https://github.com/keeporsweep/keeporsweep/pull/6, thank you @rullzer! :)
